
import React from 'react';
import { 
  BarChart, Bar, 
  LineChart, Line, 
  PieChart, Pie, Cell, 
  XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer 
} from 'recharts';
import { MOCK_VELOCITY_DATA, MOCK_TOKEN_USAGE, MOCK_OUTCOME_DATA, MOCK_FAILURE_REASONS } from '../constants';
import Button from './Button';
import { 
  CloudDownloadIcon, 
  CalendarIcon, 
  ArrowUpIcon, 
  ZapIcon, 
  AlertCircleIcon, 
  ActivityIcon 
} from './Icons';

const Analytics: React.FC = () => {
  return (
    <div className="p-8 max-w-7xl mx-auto space-y-8 animate-in fade-in duration-500 pb-20">
      
      {/* 1. Toolbar */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-semibold text-white tracking-tight">Analytics & Insights</h1>
          <p className="text-slate-400 mt-1">Measuring the ROI of Agentic Engineering</p>
        </div>
        <div className="flex items-center space-x-3">
          <div className="flex items-center bg-slate-800 border border-slate-700 rounded px-3 py-1.5 text-xs text-slate-300 cursor-pointer hover:border-slate-600 transition-colors">
            <CalendarIcon size={14} className="mr-2 text-slate-500" />
            This Sprint (Oct 10 - Oct 24)
          </div>
          <Button variant="secondary" size="sm" icon={<CloudDownloadIcon size={14} />}>Export CSV</Button>
        </div>
      </div>

      {/* 2. KPI Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <KpiCard 
          label="Velocity" 
          value="42 Points" 
          trend="↑ 12%" 
          trendPositive={true} 
          sub="vs last sprint" 
        />
        <KpiCard 
          label="AI Contribution" 
          value="65%" 
          sub="Generated by Agents" 
          highlight="indigo"
        />
        <KpiCard 
          label="Token Cost" 
          value="$4.20" 
          trend="↓ $0.50" 
          trendPositive={true} 
          sub="Efficient scaling" 
        />
        <KpiCard 
          label="Est. Time Saved" 
          value="14 Hours" 
          sub="Based on automation" 
          highlight="emerald"
        />
      </div>

      {/* 3. Main Charts Row */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        
        {/* Velocity Chart */}
        <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-6 flex flex-col h-[400px]">
           <div className="flex items-center justify-between mb-6">
              <h3 className="text-sm font-bold text-slate-300 uppercase tracking-widest flex items-center">
                 <ActivityIcon size={14} className="mr-2 text-indigo-400" />
                 Sprint Velocity Breakdown
              </h3>
           </div>
           <div className="flex-1 min-h-0">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={MOCK_VELOCITY_DATA} margin={{ top: 20, right: 30, left: 0, bottom: 0 }}>
                  <XAxis dataKey="name" stroke="#475569" fontSize={10} axisLine={false} tickLine={false} />
                  <YAxis stroke="#475569" fontSize={10} axisLine={false} tickLine={false} />
                  <Tooltip 
                    contentStyle={{ backgroundColor: '#1e293b', border: '1px solid #334155', color: '#f8fafc', fontSize: '12px' }}
                    cursor={{ fill: '#334155', opacity: 0.2 }}
                  />
                  <Legend iconType="circle" wrapperStyle={{ fontSize: '10px', paddingTop: '20px' }} />
                  <Bar dataKey="human" name="Human Completed" stackId="a" fill="#6366f1" radius={[0, 0, 0, 0]} />
                  <Bar dataKey="agent" name="Agent Completed" stackId="a" fill="#4f46e5" radius={[4, 4, 0, 0]} opacity={0.8} />
                </BarChart>
              </ResponsiveContainer>
           </div>
        </div>

        {/* Token Consumption */}
        <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-6 flex flex-col h-[400px]">
           <div className="flex items-center justify-between mb-6">
              <h3 className="text-sm font-bold text-slate-300 uppercase tracking-widest flex items-center">
                 <ZapIcon size={14} className="mr-2 text-amber-400" />
                 Daily Token Consumption
              </h3>
              <div className="text-[10px] font-mono text-slate-500">BUDGET: 100k/day</div>
           </div>
           <div className="flex-1 min-h-0">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={MOCK_TOKEN_USAGE}>
                  <XAxis dataKey="date" stroke="#475569" fontSize={10} axisLine={false} tickLine={false} />
                  <YAxis stroke="#475569" fontSize={10} axisLine={false} tickLine={false} />
                  <Tooltip 
                    contentStyle={{ backgroundColor: '#1e293b', border: '1px solid #334155', color: '#f8fafc', fontSize: '12px' }}
                  />
                  <Line type="monotone" dataKey="tokens" stroke="#f59e0b" strokeWidth={3} dot={{ fill: '#f59e0b', r: 4 }} activeDot={{ r: 6 }} />
                  <Line type="monotone" dataKey="budget" stroke="#475569" strokeDasharray="5 5" dot={false} strokeWidth={1} />
                </LineChart>
              </ResponsiveContainer>
           </div>
        </div>

      </div>

      {/* 4. Bottom Row: Agent Health */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Outcome Distribution */}
        <div className="lg:col-span-1 bg-slate-800/50 border border-slate-700 rounded-xl p-6 flex flex-col h-[350px]">
            <h3 className="text-sm font-bold text-slate-300 uppercase tracking-widest mb-6">Outcome Distribution</h3>
            <div className="flex-1 min-h-0 flex items-center justify-center">
                <ResponsiveContainer width="100%" height="100%">
                    <PieChart>
                        <Pie
                            data={MOCK_OUTCOME_DATA}
                            innerRadius={60}
                            outerRadius={80}
                            paddingAngle={5}
                            dataKey="value"
                        >
                            {MOCK_OUTCOME_DATA.map((entry, index) => (
                                <Cell key={`cell-${index}`} fill={entry.color} />
                            ))}
                        </Pie>
                        <Tooltip contentStyle={{ backgroundColor: '#1e293b', border: '1px solid #334155' }} />
                        <Legend verticalAlign="bottom" wrapperStyle={{ fontSize: '10px' }} />
                    </PieChart>
                </ResponsiveContainer>
            </div>
        </div>

        {/* Failure Log Summary */}
        <div className="lg:col-span-2 bg-slate-800/50 border border-slate-700 rounded-xl p-6 h-[350px] flex flex-col">
            <div className="flex items-center justify-between mb-4">
                <h3 className="text-sm font-bold text-slate-300 uppercase tracking-widest">Failure Bottlenecks (Top 5)</h3>
                <Button variant="ghost" size="sm" className="text-[10px]">View Full Log</Button>
            </div>
            <div className="flex-1 overflow-y-auto custom-scrollbar space-y-2 pr-2">
                {MOCK_FAILURE_REASONS.map((reason, idx) => (
                    <div key={idx} className="flex items-center justify-between p-3 bg-slate-900 border border-slate-800 rounded group hover:border-red-500/30 transition-all cursor-pointer">
                        <div className="flex items-center">
                            <div className="w-8 h-8 rounded bg-red-500/10 text-red-500 flex items-center justify-center mr-4 border border-red-500/20">
                                <AlertCircleIcon size={16} />
                            </div>
                            <span className="text-sm text-slate-300 font-medium group-hover:text-red-300 transition-colors">{reason.reason}</span>
                        </div>
                        <div className="flex items-center">
                            <span className="text-xs font-mono text-slate-500 mr-3">{reason.count} incidents</span>
                            <ChevronRightIcon size={14} className="text-slate-700" />
                        </div>
                    </div>
                ))}
                {MOCK_FAILURE_REASONS.length === 0 && (
                    <div className="flex flex-col items-center justify-center h-full text-slate-600 opacity-50">
                        <ActivityIcon size={32} className="mb-2" />
                        <p>No systemic failures detected</p>
                    </div>
                )}
            </div>
        </div>

      </div>

    </div>
  );
};

const KpiCard: React.FC<{ 
  label: string; 
  value: string; 
  trend?: string; 
  trendPositive?: boolean; 
  sub: string;
  highlight?: 'indigo' | 'emerald' | 'amber';
}> = ({ label, value, trend, trendPositive, sub, highlight }) => (
    <div className="bg-slate-850 p-5 rounded-xl border border-slate-700 shadow-sm relative overflow-hidden group hover:border-slate-600 transition-all">
        {highlight && (
            <div className={`absolute top-0 right-0 w-20 h-20 bg-${highlight}-500/5 rounded-bl-full -mr-8 -mt-8`} />
        )}
        <p className="text-xs text-slate-500 font-bold uppercase tracking-widest mb-1">{label}</p>
        <div className="flex items-baseline space-x-3 mb-1">
            <span className="text-2xl font-bold text-white tracking-tight">{value}</span>
            {trend && (
                <span className={`text-[10px] font-bold px-1.5 py-0.5 rounded border ${
                    trendPositive ? 'text-emerald-400 bg-emerald-500/5 border-emerald-500/10' : 'text-red-400 bg-red-500/5 border-red-500/10'
                }`}>
                    {trend}
                </span>
            )}
        </div>
        <p className="text-xs text-slate-500 leading-none">{sub}</p>
    </div>
);

const ChevronRightIcon: React.FC<{ size?: number; className?: string }> = ({ size = 16, className = "" }) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="1.5"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
  >
    <polyline points="9 18 15 12 9 6" />
  </svg>
);

export default Analytics;
